In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
dharsha=pd.read_csv("C:/Users/ELCOT/Downloads/sales_data.csv")

In [6]:
print(dharsha.loc[0])

OrderID             1031
Date          2026-01-01
Product       Smartphone
Category     Electronics
Quantity               3
UnitPrice            800
Name: 0, dtype: object

In [10]:
print(dharsha.loc[0:19])

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
6      1055  2026-01-03  Headphones  Accessories         1        150
7      1020  2026-01-03      Laptop  Electronics         1       1200
8      1082  2026-01-03  Smartphone  Electronics         4        800
9      1085  2026-01-04      Laptop  Electronics         1       1200
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
12     1017  2026-01-04  Smartwatch  Accessories         3        250
13     1063  2026-01-04  Smartwatch  Accessories         4        250
14     1056  2026-01-05  Smartwatch  Accessories         4        250
15     1091  2026-01-06  Smartwatch  Accessories         4        250
16     1027  2026-01-06      Tablet  Electronics         2        450
17     1061  2026-01-07  Headphones  Accessories         3        150
18     1058  2026-01-07      Laptop  Electronics         2       1200
19     1077  2026-01-07  Headphones  Accessories         2        150

In [9]:
print(dharsha.iloc[0:10,0:6])

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200
4     1023  2026-01-02      Tablet  Electronics         4        450
5     1072  2026-01-02  Smartphone  Electronics         4        800
6     1055  2026-01-03  Headphones  Accessories         1        150
7     1020  2026-01-03      Laptop  Electronics         1       1200
8     1082  2026-01-03  Smartphone  Electronics         4        800
9     1085  2026-01-04      Laptop  Electronics         1       1200

In [11]:
print(dharsha.columns)

Index(['OrderID', 'Date', 'Product', 'Category', 'Quantity', 'UnitPrice'], dtype='str')

In [12]:
print(dharsha[dharsha["Quantity"]>500])

Empty DataFrame
Columns: [OrderID, Date, Product, Category, Quantity, UnitPrice]
Index: []

In [13]:
print(dharsha[dharsha["Quantity"]<500])

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [14]:
print(dharsha[dharsha["UnitPrice"]>500|(dharsha["Quantity"]>5)])

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [15]:
dharsha.sort_values("Quantity",ascending=False)

    OrderID        Date     Product     Category  Quantity  UnitPrice
8      1082  2026-01-03  Smartphone  Electronics         4        800
10     1088  2026-01-04      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
4      1023  2026-01-02      Tablet  Electronics         4        450
24     1087  2026-01-08      Laptop  Electronics         4       1200
..      ...         ...         ...          ...       ...        ...
76     1064  2026-01-25      Tablet  Electronics         1        450
85     1065  2026-01-28  Smartwatch  Accessories         1        250
95     1026  2026-01-30      Tablet  Electronics         1        450
92     1096  2026-01-29  Smartwatch  Accessories         1        250
93     1035  2026-01-29      Laptop  Electronics         1       1200

[100 rows x 6 columns]

In [16]:
dharsha.sort_values(["Quantity","Product"],ascending=[True,False])

    OrderID        Date     Product     Category  Quantity  UnitPrice
34     1051  2026-01-12      Tablet  Electronics         1        450
72     1024  2026-01-24      Tablet  Electronics         1        450
76     1064  2026-01-25      Tablet  Electronics         1        450
95     1026  2026-01-30      Tablet  Electronics         1        450
61     1008  2026-01-21  Smartwatch  Accessories         1        250
..      ...         ...         ...          ...       ...        ...
46     1044  2026-01-16      Laptop  Electronics         4       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
71     1015  2026-01-24      Laptop  Electronics         4       1200
78     1033  2026-01-26      Laptop  Electronics         4       1200
40     1066  2026-01-14  Headphones  Accessories         4        150

[100 rows x 6 columns]

In [20]:
dharsha["Total"]=dharsha["Quantity"]*dharsha["UnitPrice"]

In [21]:
dharsha["Total"]=dharsha["Quantity"]+dharsha["UnitPrice"]

In [24]:
dharsha.groupby("Category")["Product"].min()

Category
Accessories    Headphones
Electronics        Laptop
Name: Product, dtype: str

In [25]:
dharsha.groupby("Category")["Product"].max()

Category
Accessories    Smartwatch
Electronics        Tablet
Name: Product, dtype: str

In [27]:
dharsha.groupby("Category")["UnitPrice"].mean()

Category
Accessories    197.619048
Electronics    851.724138
Name: UnitPrice, dtype: float64

In [28]:
dharsha.groupby("Category")["UnitPrice"].count()

Category
Accessories    42
Electronics    58
Name: UnitPrice, dtype: int64